# Generated by Django 4.0.5 on 2022-07-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_homebg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebg',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='BG image'),
        ),
    ]
